# Task 2: Restaurant Recommendation System
# Objective
Build a content-based restaurant recommendation system that suggests restaurants based on user preferences such as cuisine and price range.

# Steps Performed
1. Imported the required Python libraries.
2. Loaded the restaurant dataset.
3. Checked and handled missing values.
4. Encoded categorical variables.
5. Selected cuisine, price range, and rating as features.
6. Applied Cosine Similarity for content-based filtering.
7. Built a recommendation function based on user preferences.
8. Tested the system with sample inputs.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/User/Downloads/Dataset.csv"); df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [3]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

# Data cleaning

In [6]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [7]:
# Handle missing values
df['Cuisines'] = df['Cuisines'].fillna('Unknown')

df['Price range'].fillna(df['Price range'].median(), inplace=True)
df['Aggregate rating'].fillna(df['Aggregate rating'].median(), inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_28264\3554690981.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price range'].fillna(df['Price range'].median(), inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_28264\3554690981.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Aggregate rating'].fillna(df['Aggregate rating'].median(), inplace=True)

In [8]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

# Data preprocessing

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Cuisines'] = le.fit_transform(df['Cuisines'])
df['Has Table booking'] = le.fit_transform(df['Has Table booking'])
df['Has Online delivery'] = le.fit_transform(df['Has Online delivery'])
print(df)

      Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City
1           6304287          Izakaya Kikufuji           162       Makati City
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City
3           6318506                      Ooma           162  Mandaluyong City
4           6314302               Sambo Kojin           162  Mandaluyong City
...             ...                       ...           ...               ...
9546        5915730               Naml۱ Gurme           208         ��stanbul
9547        5908749              Ceviz A��ac۱           208         ��stanbul
9548        5915807                     Huqqa           208         ��stanbul
9549        5916112               A���k Kahve           208         ��stanbul
9550        5927402  Walter's Coffee Roastery           208         ��stanbul

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...
3     Third Floor, Mega Fashion Hall, SM Megamall, O...
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...
...                                                 ...
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...

                                        Locality  \
0      Century City Mall, Poblacion, Makati City
1     Little Tokyo, Legaspi Village, Makati City
2     Edsa Shangri-La, Ortigas, Mandaluyong City
3         SM Megamall, Ortigas, Mandaluyong City
4         SM Megamall, Ortigas, Mandaluyong City
...                                          ...
9546                                    Karak�_y
9547                                   Ko��uyolu
9548                                 Kuru�_e��me
9549                                 Kuru�_e��me
9550                                        Moda

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508
...                                                 ...         ...
9546                                Karak�_y, ��stanbul   28.977392
9547                               Ko��uyolu, ��stanbul   29.041297
9548                             Kuru�_e��me, ��stanbul   29.034640
9549                             Kuru�_e��me, ��stanbul   29.036019
9550                                    Moda, ��stanbul   29.026016

       Latitude  Cuisines  ...          Currency Has Table booking  \
0     14.565443       920  ...  Botswana Pula(P)                 1
1     14.553708      1111  ...  Botswana Pula(P)                 1
2     14.581404      1671  ...  Botswana Pula(P)                 1
3     14.585318      1126  ...  Botswana Pula(P)                 0
4     14.584450      1122  ...  Botswana Pula(P)                 1
...         ...       ...  ...               ...               ...
9546  41.022793      1813  ...  Turkish Lira(TL)                 0
9547  41.009847      1825  ...  Turkish Lira(TL)                 0
9548  41.055817      1110  ...  Turkish Lira(TL)                 0
9549  41.057979      1657  ...  Turkish Lira(TL)                 0
9550  40.984776       331  ...  Turkish Lira(TL)                 0

      Has Online delivery  Is delivering now Switch to order menu Price range  \
0                       0                 No                   No           3
1                       0                 No                   No           3
2                       0                 No                   No           4
3                       0                 No                   No           4
4                       0                 No                   No           4
...                   ...                ...                  ...         ...
9546                    0                 No                   No           3
9547                    0                 No                   No           3
9548                    0                 No                   No           4
9549                    0                 No                   No           4
9550                    0                 No                   No           2

      Aggregate rating  Rating color Rating text Votes
0                  4.8    Dark Green   Excellent   314
1                  4.5    Dark Green   Excellent   591
2                  4.4         Green   Very Good   270
3                  4.9    Dark Green   Excellent   365
4                  4.8    Dark Green   Excellent   229
...                ...           ...         ...   ...
9546               4.1         Green   Very Good   788
9547               4.2         Green   Very Good  1034
9548               3.7        Yellow        Good   661
9549               4.0         Green   Very Good   901
9550               4.0         Green   Very Good   591

[9551 rows x 21 columns]

In [10]:
# create Feature Matrix
features = df[['Cuisines', 'Price range', 'Aggregate rating']]; features

      Cuisines  Price range  Aggregate rating
0          920            3               4.8
1         1111            3               4.5
2         1671            4               4.4
3         1126            4               4.9
4         1122            4               4.8
...        ...          ...               ...
9546      1813            3               4.1
9547      1825            3               4.2
9548      1110            4               3.7
9549      1657            4               4.0
9550       331            2               4.0

[9551 rows x 3 columns]

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(features); similarity

array([[1.        , 0.99999916, 0.99999629, ..., 0.99999817, 0.99999571,
        0.99997256],
       [0.99999916, 1.        , 0.99999895, ..., 0.99999933, 0.99999862,
        0.99996215],
       [0.99999629, 0.99999895, 1.        , ..., 0.99999902, 0.99999998,
        0.99994869],
       ...,
       [0.99999817, 0.99999933, 0.99999902, ..., 1.        , 0.99999887,
        0.99995874],
       [0.99999571, 0.99999862, 0.99999998, ..., 0.99999887, 1.        ,
        0.99994667],
       [0.99997256, 0.99996215, 0.99994869, ..., 0.99995874, 0.99994667,
        1.        ]], shape=(9551, 9551))

In [12]:
def recommend_restaurants(index, top_n=5):
    
    similarity_scores = list(enumerate(similarity[index]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True)

    similarity_scores = similarity_scores[1:top_n+1]

    restaurant_indices = [i[0] for i in similarity_scores]

    return df.iloc[restaurant_indices][
        ['Restaurant Name','Cuisines','Price range','Aggregate rating']]
    
recommend_restaurants(10)

        Restaurant Name  Cuisines  Price range  Aggregate rating
2100    Oriental Fusion       599            2               3.3
1710  Hong Kong Express       588            2               3.2
2103        Speedy Chow       588            2               3.2
2599            Mr Wong       588            2               3.2
6181  Hong Kong Express       588            2               3.2

# Conclusion
A Content-Based Restaurant Recommendation System was successfully developed using Python, Pandas, and Scikit-learn. The dataset was preprocessed by handling missing values and encoding categorical variables. The system uses Cuisine, Price Range, and Aggregate Rating as recommendation features and applies Cosine Similarity to recommend restaurants that best match the user's preferences. The generated recommendations were relevant and demonstrated the effectiveness of content-based filtering in providing personalized restaurant suggestions.